version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-gamearena
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - gamearena-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend-gamearena
    restart: always
    env_file:
      - .env
    environment:
      SPRING_PROFILES_ACTIVE: main
      DB_HOST: mysql
    ports:
      - "${APPLICATION_PORT}:8080"
    depends_on:
      - mysql
    networks:
      - gamearena-network
    volumes:
      - ./logs:/app/logs

volumes:
  mysql_data:
    driver: local

networks:
  gamearena-network:
    driver: bridge